name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploying to Surge
    env:
      CI: false  # Set CI environment variable to false
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Navigate to backend directory and install npm dependencies
        run: |
          cd backend
          npm install

      - name: Create ESLint configuration
        run: |
          cd backend
          echo '{
              "env": {
                  "browser": true,
                  "commonjs": true,
                  "es2021": true,
                  "node": true
              },
              "extends": "eslint:recommended",
              "parserOptions": {
                  "ecmaVersion": 12
              },
              "rules": {
                  "indent": ["error", 2],
                  "linebreak-style": ["error", "unix"],
                  "quotes": ["error", "single"],
                  "semi": ["error", "always"]
              }
          }' > .eslintrc.json

      - name: Build the application
        run: |
          cd backend
          npm run build  # Run the build script defined in package.json

      - name: Run the backend application
        run: |
          cd backend
          npm start &

      - name: Install Surge
        run: npm install -g surge

      - name: Run surge
        run: |
          surge ./backend/dist weatherapp_prodelect.surge.sh --token ${{ secrets.SURGE_TOK }}
