name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploying to Surge
    env:
      CI: false  # Set CI environment variable to false
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Navigate to backend directory and install npm dependencies
        run: |
          cd backend
          npm install

      - name: Build the application
        run: |
          cd backend
          npm run build  # Adjust if your application uses a different build script

      - name: Run the backend application
        run: |
          cd backend
          npm start &

      - name: Install Surge
        run: npm install -g surge

      - name: Deploy to Surge
        env:
          SURGE_TOKEN: ${{ secrets.SURGE_TOK }}
        run: |
          cd backend
          surge ./build weatherapp_prodelect.surge.sh --token $SURGE_TOKEN
