name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploying to Surge
    env:
      CI: false  # Set CI environment variable to false
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Navigate to backend directory and install npm dependencies
        run: |
          cd backend
          npm install

      - name: Run the backend application
        run: |
          cd backend
          npm start &

      - name: Install Surge
        run: npm install -g surge

      - name: Run surge
        run: |
          surge ./backend/build weatherapp_prodelect.surge.sh --token ${{ secrets.SURGE_TOKEN }}
