name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploying to Surge
    env:
      CI: false  # Set CI environment variable to false
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install npm dependencies
        run: npm install

      - name: Run the backend application
        run: npm start

      - name: Install Surge
        run: npm install -g surge

      - name: Deploy to Surge
        run: |
          surge ./ build weatherApp_proelec.surge.sh --token ${{ secrets.SURGE_TOKEN }}
